# Generated by Django 4.2.2 on 2023-08-26 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporate_name', models.CharField(default='', max_length=255)),
                ('firstname', models.CharField(default='', max_length=255)),
                ('middlename', models.CharField(default='', max_length=255)),
                ('lastname', models.CharField(default='', max_length=255)),
                ('age', models.IntegerField(default=18)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('address1', models.CharField(default='', max_length=255)),
                ('address2', models.CharField(default='', max_length=255)),
                ('city_district', models.CharField(default='', max_length=255)),
                ('state_province', models.CharField(default='', max_length=255)),
                ('postal_code', models.CharField(default='', max_length=255)),
                ('country', models.CharField(default='Nigeria', max_length=255)),
                ('contact_pics', models.ImageField(null=True, upload_to='images/contact_pics')),
                ('social_id', models.ImageField(null=True, upload_to='images/social_id')),
                ('self_registered', models.BooleanField(default=True)),
                ('payment_frequency', models.CharField(default='MONTHLY', max_length=255)),
                ('next_pay_reminder', models.DateTimeField()),
                ('contact_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contacttype')),
            ],
        ),
    ]
