# Generated by Django 4.2.2 on 2023-08-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='address1',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='address2',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='city_district',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='country',
            field=models.CharField(blank=True, default='Nigeria', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='next_pay_reminder',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='payment_frequency',
            field=models.CharField(blank=True, default='MONTHLY', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='state_province',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
