# Generated by Django 4.2.2 on 2023-08-26 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contacts_address1_alter_contacts_address2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacttype',
            old_name='contact_type',
            new_name='name',
        ),
    ]
