# Generated by Django 4.2.2 on 2023-09-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_contacts_contact_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='gender',
            field=models.CharField(default='', max_length=255),
        ),
    ]
