# Generated by Django 4.2.2 on 2023-09-22 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
        ('uiconfig', '0003_uimasterrooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedRestaurantMeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('room_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.meal')),
            ],
        ),
    ]
