# Generated by Django 4.2.2 on 2023-09-08 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_bill_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='charge',
            new_name='rate',
        ),
    ]
