# Generated by Django 4.2.2 on 2023-09-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_rename_charge_bill_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='active_reservation_token',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
