# Generated by Django 4.2.2 on 2023-10-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_bill_active_reservation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='itemid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
