# Generated by Django 4.2.2 on 2023-10-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_bill_itemid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
