# Generated by Django 4.2.2 on 2023-08-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
