# Generated by Django 4.2.2 on 2023-08-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservations_check_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='reservation_token',
            field=models.CharField(default='', max_length=255),
        ),
    ]
