# Generated by Django 4.2.2 on 2023-08-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservations_reservation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='check_in',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='check_out',
            field=models.CharField(default='', max_length=255),
        ),
    ]
