# Generated by Django 4.2.2 on 2023-09-06 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_alter_reservations_reservation_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservations',
            old_name='rate',
            new_name='room_rate',
        ),
    ]
