# Generated by Django 4.2.2 on 2023-09-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_alter_reservations_check_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='is_history',
            field=models.BooleanField(default=False),
        ),
    ]
