# Generated by Django 4.2.2 on 2023-09-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_reservations_history_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='reservations',
            name='addons',
            field=models.JSONField(default=[]),
        ),
    ]
