# Generated by Django 4.2.2 on 2023-09-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_addons_reservations_addons'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddonsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('total_price', models.CharField(max_length=255)),
                ('reservation_token', models.CharField(max_length=255)),
                ('status', models.CharField(default='PENDING', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='addons',
            name='max_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
