# Generated by Django 4.2.2 on 2023-09-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_addonsrequest_addons_max_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='package',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
