# Generated by Django 4.2.2 on 2023-10-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_bill_qty'),
        ('reservations', '0016_remove_reservations_no_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='bills',
            field=models.ManyToManyField(default=[], to='billing.bill'),
        ),
    ]
