# Generated by Django 4.2.2 on 2023-10-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0017_reservations_bills'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='address1',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reservations',
            name='email',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reservations',
            name='firstname',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reservations',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reservations',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reservations',
            name='surname',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
