# Generated by Django 4.2.2 on 2023-10-29 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0018_reservations_address1_reservations_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservations',
            old_name='address1',
            new_name='address',
        ),
    ]
