# Generated by Django 4.2.2 on 2023-08-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rates',
            name='rate_type',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
