# Generated by Django 4.2.2 on 2023-08-26 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_rates_rate_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomandrates',
            old_name='rate',
            new_name='rate_per_night',
        ),
    ]
