# Generated by Django 4.2.2 on 2023-10-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SweetError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_name', models.CharField(max_length=20)),
                ('error_lines', models.JSONField(default=[])),
                ('sweet_error', models.CharField(max_length=255)),
                ('raw_traceback', models.TextField(default='')),
                ('parsed_traceback', models.TextField(default='')),
                ('is_resolved', models.BooleanField(default=False)),
                ('is_permitted', models.BooleanField(default=False)),
                ('is_legacy', models.BooleanField(default=False)),
            ],
        ),
    ]
