# Generated by Django 4.2.2 on 2023-08-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='room_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='roomtype',
            old_name='generic_type_image',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_no',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
