# Generated by Django 4.2.2 on 2023-08-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_rename_room_image_rooms_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rooms',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
    ]
