# Generated by Django 4.2.2 on 2023-08-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_rooms_is_available_rooms_is_occupied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
