# Generated by Django 4.2.2 on 2023-08-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_rooms_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='require_advance_payment',
            field=models.BooleanField(default=True),
        ),
    ]
