# Generated by Django 4.2.2 on 2023-08-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_roomtype_require_advance_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
