# Generated by Django 4.2.2 on 2023-08-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_roomtype_advance_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='amenities',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='amenities',
            field=models.ManyToManyField(default=[], to='rooms.amenities'),
        ),
    ]
