# Generated by Django 4.2.2 on 2023-08-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_remove_roomtype_amenities_roomtype_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenities',
            name='charge_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='amenities',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
