# Generated by Django 4.2.2 on 2023-08-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_amenities_charge_amount_amenities_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenities',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
