# Generated by Django 4.2.2 on 2023-09-02 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_rename_contact_type_contacttype_name'),
        ('rooms', '0009_amenities_updated_at'),
    ]

    operations = [

        migrations.AddField(
            model_name='bedtype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='check_in_date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='check_out_date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='occupant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contacts.contacts'),
        ),
        migrations.AlterField(
            model_name='floors',
            name='floor_no',
            field=models.IntegerField(unique=True),
        ),
    ]
