# Generated by Django 4.2.2 on 2023-09-02 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_rename_name_floors_floor_name_bedtype_created_at_and_more'),
    ]

    operations = [
       
    ]
