# Generated by Django 4.2.2 on 2023-09-02 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_rename_name_floors_floor_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floors',
            old_name='name',
            new_name='floor_name',
        ),
        migrations.AlterField(
            model_name='rooms',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rooms.floors'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rooms.roomtype'),
        ),
    ]
