# Generated by Django 4.2.2 on 2023-09-02 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_rename_contact_type_contacttype_name'),
        ('rooms', '0012_rename_name_floors_floor_name_alter_rooms_floor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='occupant',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contacts.contacts'),
        ),
    ]
