# Generated by Django 4.2.2 on 2023-09-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0013_alter_rooms_occupant'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
