# Generated by Django 4.2.2 on 2023-09-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0014_rooms_advance_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_no',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
