# Generated by Django 4.2.2 on 2023-09-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0016_rooms_room_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='require_advance_payment',
            field=models.BooleanField(default=False),
        ),
    ]
