# Generated by Django 4.2.2 on 2023-09-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0017_alter_roomtype_require_advance_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='no_adults',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='no_children',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='no_xtra_adults',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
