# Generated by Django 4.2.2 on 2023-09-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0018_rooms_no_adults_rooms_no_children_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='active_reservation_token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
