# Generated by Django 4.2.2 on 2023-09-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0019_rooms_active_reservation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='is_checked_in',
            field=models.BooleanField(default=False),
        ),
    ]
