# Generated by Django 4.2.2 on 2023-09-08 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_rename_contact_type_contacttype_name'),
        ('rooms', '0020_rooms_is_checked_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='occupant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contacts.contacts'),
        ),
    ]
