# Generated by Django 4.2.2 on 2023-09-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0021_alter_rooms_occupant'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='is_clean',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='maintenance_block',
            field=models.BooleanField(default=False),
        ),
    ]
