# Generated by Django 4.2.2 on 2023-09-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0024_rooms_further_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='size',
            field=models.CharField(blank=True, default='45 m2', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='view',
            field=models.CharField(blank=True, default="The statue of Ali and Nino - a moving sculptural composition in Batumi Boulevard, is one of the attractions of Georgia's Black Sea resort", max_length=255, null=True),
        ),
    ]
