# Generated by Django 4.2.2 on 2023-09-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0025_rooms_size_rooms_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='no_beds',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
