# Generated by Django 4.2.2 on 2023-09-15 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0027_roomscomplaints'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomscomplaints',
            old_name='receipient',
            new_name='assigned_to',
        ),
        migrations.RenameField(
            model_name='roomscomplaints',
            old_name='room_no',
            new_name='rooms',
        ),
    ]
