# Generated by Django 4.2.2 on 2023-09-16 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0029_roomscomplaints_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='is_clean',
            new_name='is_ready',
        ),
    ]
