# Generated by Django 4.2.2 on 2023-09-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0030_rename_is_clean_rooms_is_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='dead_reservation_token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
