# Generated by Django 4.2.2 on 2023-09-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0031_rooms_dead_reservation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='checked_out_date',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
