# Generated by Django 4.2.2 on 2023-09-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0032_rooms_checked_out_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='amenities',
            field=models.ManyToManyField(default=[], to='rooms.amenities'),
        ),
    ]
