# Generated by Django 4.2.2 on 2023-09-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0033_rooms_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='room_rate',
            field=models.DecimalField(decimal_places=2, default=1500.0, max_digits=20),
        ),
    ]
