# Generated by Django 4.2.2 on 2023-09-28 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0034_roomtype_room_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='no_children',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='no_xtra_adults',
        ),
    ]
