# Generated by Django 4.2.2 on 2023-08-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_users_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='address1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='users',
            name='address2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='firstname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='othername',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='surname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
