# Generated by Django 4.2.2 on 2023-08-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_users_address1_users_address2_users_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
