# Generated by Django 4.2.2 on 2023-08-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_alter_users_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffCommentary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.CharField(default='', max_length=100, null=True)),
                ('comment', models.TextField(default='', max_length=1000, null=True)),
                ('comment_by', models.CharField(default='', max_length=255, null=True)),
                ('comment_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='commentary',
            field=models.ManyToManyField(default=[], to='authentication.staffcommentary'),
        ),
    ]
