# Generated by Django 4.2.2 on 2023-08-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_staffcommentary_users_commentary'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
