# Generated by Django 4.2.2 on 2023-09-09 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_allowances_salary'),
        ('authentication', '0016_users_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='allowances',
            field=models.ManyToManyField(default=[], to='finance.allowances'),
        ),
        migrations.AddField(
            model_name='users',
            name='basic_salary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.salary'),
        ),
        migrations.AddField(
            model_name='users',
            name='is_sacked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='salary_topup',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.CreateModel(
            name='StaffRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(default='', max_length=100, null=True)),
                ('work_description', models.TextField(default='', max_length=1000, null=True)),
                ('salary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.salary')),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.staffroles'),
        ),
    ]
