# Generated by Django 4.2.2 on 2023-09-09 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_users_allowances_users_basic_salary_users_is_sacked_and_more'),
    ]

    operations = [
        
    ]
