# Generated by Django 4.2.2 on 2023-09-09 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_remove_users_is_sacked_remove_users_is_suspended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_sacked',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_suspended',
        ),
    ]
