# Generated by Django 4.2.2 on 2023-09-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_remove_users_is_sacked_remove_users_is_suspended'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_sacked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
    ]
